SELECT 
ins.ANIMAL_ID, ins.ANIMAL_TYPE, ins.NAME
FROM ANIMAL_INS AS ins RIGHT OUTER JOIN ANIMAL_OUTS AS outs
USING (ANIMAL_ID)
WHERE (ins.SEX_UPON_INTAKE != outs.SEX_UPON_OUTCOME) 
AND ((outs.SEX_UPON_OUTCOME LIKE 'Spayed%') OR (outs.SEX_UPON_OUTCOME LIKE 'Neutered%'))
ORDER BY ins.ANIMAL_ID;